export const ALERT_EXPIRATION_PERIOD = 4000;

export const LOCAL_STORAGE_TOKEN_KEY =
    "U2FsdGVkX1/G0spCYq44fQCTDWSVO6gq2/UDLKJSLKAFJKLADFDS";
export const LOCAL_STORAGE_USER_KEY =
    "G0spCYq44fQCTDWSVO6gq2/U2FsdGVkX1/UDLKJSLKAFJKLADFDS";
export const PREV_LINK_LOCAL_STORAGE_KEY =
    "U2FsdGVkX1/wKjkfljasdlkjfkajdaPpveuMtd+sqe8pr64Dq2r";
export const DEVICE_DETAILS_LOCAL_STORAGE_KEY =
    "U2FsdGVkX18VgmL9lt/jkldfjklsjfdau3rWg1q6h4lsc=";